### ISSUE TITLE
Debugging .NET core projects

### ISSUE THREAD

**Issue by enricosada** [ionide/ionide-vscode-fsharp#366]
Debugging of .net core console app (`netcoreapp1.0`, `netcoreapp1.1`) works inside VS Code

Using the new fsproj.

Like c# with csproj now using c# extension or ominisharp

- [x] `F5` run in debug
- [x] create `launch.json` with doesnt exists 
- [x] breakpoints
- [x] watch
- [x] stack trace

## TODO

- [x] compiler emit pdb in portable pdb format
- [x] vscode debugging engine recognize f# console and pdb

**Comment by adamchester** [comment]
👍 😍

**Comment by xperiandri** [comment]
What about `netcoreapp1.1`?

**Comment by enricosada** [comment]
@xperiandri yes, that too. is the same. It's just i copy/pasted an old issue (before 1.1 :D)

Added https://github.com/OmniSharp/omnisharp-vscode/issues/1257 to ask debugger team more info. 
atm with rc4 and `FSharp.NET.Sdk` 1.0.0 debugging sort of work (but no breakpoints) without hacks

![image](https://cloud.githubusercontent.com/assets/147243/23175285/32bf2864-f85f-11e6-8558-3cde7ab9adf4.png)

Now i think should be ok to start thinking seriously about this issue because:

- msbuild/sdk is ok and stable
- fsproj works
- portable pdb are generated by latest version of fsc compiler
- fsharp.core should be ok too
- basic debugger works (debug a program with `failwith` to see)

**Comment by xperiandri** [comment]
I don't know why but it does not work at all. And even F# language service does not appear in output.
How can I diagnose the issue?

**Comment by enricosada** [comment]
it's doesnt matter the f# intellisense i think (it doesnt work yet).
try:

- create rc4 c# console
- debug it correctly, so we are sure things works
- clone my repro (see other pr) and follow instruction in readme

**Comment by xperiandri** [comment]
I can't set a breakpoint and statement completion (IntelliSense) does not work to.
But if I run it within debugger and got exception it appears in editor.
Is it a right behavior for now?

**Comment by enricosada** [comment]
> I can't set a breakpoint and statement completion (IntelliSense) does not work to.
> But if I run it within debugger and got exception it appears in editor.

yes @xperiandri , that's the current status, please read https://github.com/OmniSharp/omnisharp-vscode/issues/1257

**Comment by xperiandri** [comment]
OK, so this means there is nothing related to Ionide, just an issue with .NET Core debugging in VS Code, right?

**Comment by enricosada** [comment]
I don't know who should enable breakpoints. Maybe ionide need to do that by api. Or not. 
This issue is there as high level feature request. The other is asking more info directly to the team ppl redirected me to

**Comment by Krzysztof-Cieslak** [comment]
Neither extension (Ionide or omnisharp) doesn't define that you can use breakpoints on F# files in their `project.json`s. Maybe adding it to omnisharp would be enough. Dirty workaround (used also for Fable, and source-map based debugging) is to install `mono-debugger` - this will let you put breakpoints in F# files. 

I still think that they should release debugger as separate extension just like `mono-debugger`

**Comment by xperiandri** [comment]
Indeed! Mono debugger allows to put break points.
Statement completion left...

**Comment by enricosada** [comment]
@Krzysztof-Cieslak can you comment about that in the linked issue? Maybe they can do something about that (enable by default in coreclr debugger). 

@xperiandri I'll fix intellisense soon, np about that

**Comment by richardjharding** [comment]
I think mono-debugger is only an option on non Windows?

**Comment by enricosada** [comment]
@richardjharding i tried it, addign `mono-debugger` works also on windows

@Krzysztof-Cieslak good catch. is this a good summary?

- omnisharp add build/run/debug of .net core (that should be moved to a single package agreed) 
- if adding `mono-debugger` enable F# breakpoint and enable breakpoint on coreclr debugger too (step/continue works), so is just a flag set by `mono-debugger` extension ihmo for f#, because c# works without `mono-debugger`. 

I'll try to check to see what's doing (no promises, not familiar with vscode extension codebases), so maybe we can add that in ionide and call it a day

**Comment by richardjharding** [comment]
maybe I was looking at the wrong thing - not [Mono Debug vscode extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.mono-debug)? 

I have a combined c# (specflow) f# project (canopy steps) solution that I would like to use vscode for so getting debugging working is the final piece

**Comment by Krzysztof-Cieslak** [comment]
> I think mono-debugger is only an option on non Windows?

Debugging by `mono-debugger` works only on Linux / OSX. But `mono-debugger` extension manifest enables setting breakpoints in F# files.

That's what is needed: https://github.com/Microsoft/vscode-mono-debug/blob/master/package.json#L46-L54.

I'll add it one day here anyway, when Full .Net debugger is ready

**Comment by enricosada** [comment]
@Krzysztof-Cieslak maybe is easier.

Checking source code, `mono-debugger` [enable breakpoints](https://github.com/Microsoft/vscode-mono-debug/blob/dd1348275afc2357403663b33ef0a5ff451d5ead/src/MonoDebugSession.cs#L487) [checking](https://github.com/Microsoft/vscode-mono-debug/blob/dd1348275afc2357403663b33ef0a5ff451d5ead/src/MonoDebugSession.cs#L436-L440) the [filename extension](https://github.com/Microsoft/vscode-mono-debug/blob/dd1348275afc2357403663b33ef0a5ff451d5ead/src/MonoDebugSession.cs#L21-L24)

related, also unity debugger work like `mono-debugger` but [doesnt enable f# extensions](https://github.com/Unity-Technologies/vscode-unity-debug/blob/master/UnityDebug/UnityDebugSession.cs#L23)

**Comment by enricosada** [comment]
ah manifest too, @Krzysztof-Cieslak the omnisharp for debuggers is a bit different too (as a note) but maybe that's the dropdown for choosing debugger.
Enabling `fsharp` in [package.json](https://github.com/OmniSharp/omnisharp-vscode/blob/c4c977cc5b6d9534b276a20ab89d335b555f6da2/package.json#L476-L485) should at least do it for `fsharp` editors, let's see

**Comment by enricosada** [comment]
Ok works. enable breakpoint without `mono-debugger`. thx a lot @Krzysztof-Cieslak 

I'll send pr later today.

**Comment by enricosada** [comment]
![debug-breakpoints](https://cloud.githubusercontent.com/assets/147243/23219765/3d3168cc-f920-11e6-8524-6a79eebf5dae.gif)

just f# expression eval is missing. atm is c# expression based, but that's the debug engine afaik /cc @cartermp @mrward for more info in VS and VS on mac

**Comment by mrward** [comment]
Debugging for F# .NET Core projects works in Visual Studio for Mac. It was not working in the last preview that was released preview 3. Not done a huge amount of testing. @nosami has been looking at some things I got stuck with that were not working with F# .NET Core projects in Visual Studio for Mac.

**Comment by enricosada** [comment]
@mrward no i mean, in vs on mac the debug eval (watch) of F# expression works? in vscode the expression of eval are c# based. just trying to figure if is something of engine or client

the old beore `FSharp.NET.SDk` 1.0.0 (the `dotnet-compile-fsc`) used an old compiler, so probably portablepdb were not ok. the 1.0.0 use latest released `fsc`
I'll push tomorrow a fix for that mono issue (if this is what stuck you). i was waiting some review (i'll ping ppl another time)

**Comment by mrward** [comment]
Visual Studio for Mac passes the watch expression to the .NET Core debugger for evaluation.

**Comment by Krzysztof-Cieslak** [comment]
OK, closing this one. Debugger is working with Omnisharp, we can't fix evaluator on our own (and there's issue on this in VF# repo)

**Comment by xperiandri** [comment]
What about statement completion? Is it tracked in another issue?

**Comment by enricosada** [comment]
@xperiandri the what? intellisense?

**Comment by xperiandri** [comment]
Yes
